version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/big-brother
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: deploy/start.sh
      runas: ec2-user
      timeout: 60